In [3]:
import pandas as pd
import numpy as np

In [4]:
#Initialize dataset
df = pd.read_csv("top500mangaMAL.csv")

In [5]:
#Dropping useless columnds
df = df.drop(["Manga URL", "Type", "Volumes", "Chapters", "Status", "Published", "Published Dates", "Author",
 "Serialization", "Ranked", "Popularity", "Members", "Favorites", "Score Voted By", "Synonims Titles", "English Title"], axis=1)
df

,Manga ID,Japanese Title,Genres,Score
0,2,ベルセルク,"['Action', 'Adventure', 'Demons', 'Drama', 'Fa...",9.33
1,1706,ジョジョの奇妙な冒険 Part7 STEEL BALL RUN,"['Action', 'Adventure', 'Mystery', 'Historical...",9.21
2,25,鋼の錬金術師,"['Action', 'Adventure', 'Comedy', 'Drama', 'Sh...",9.12
3,13,ONE PIECE,"['Action', 'Adventure', 'Comedy', 'Fantasy', '...",9.08
4,1,MONSTER,"['Mystery', 'Drama', 'Psychological', 'Seinen']",9.07
...,...,...,...,...
495,27967,PandoraHearts ～Caucus race～,"['Action', 'Fantasy', 'Magic', 'Supernatural']",8.12
496,48025,マギ シンドバッドの冒険,"['Action', 'Adventure', 'Fantasy', 'Shounen']",8.12
497,18074,Unknown,"['Action', 'Mecha', 'Shounen']",8.11
498,35003,山田くんと7人の魔女,"['Comedy', 'Mystery', 'Romance', 'School', 'Sh...",8.11
499,41847,それでも世界は美しい,"['Adventure', 'Fantasy', 'Romance', 'Shoujo']",8.11

In [6]:
#List of all the genres
genres = df["Genres"][0]
genres

"['Action', 'Adventure', 'Demons', 'Drama', 'Fantasy', 'Horror', 'Supernatural', 'Military', 'Psychological', 'Seinen']"

In [7]:
#Look at ngrams in Genre
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
tfidf = vectorizer.fit_transform(df["Genres"])

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
#Input
genre = "Adventure, Action, Fantasy, Demons, Drama"
#Term Frequency Inverse Document Frequency, converts text into numbers essentially and makes them unique values
query_vec = vectorizer.transform([genre])
#Find simlar values that match with the query
similarity = cosine_similarity(query_vec, tfidf).flatten()
#Get top 5 most similar to input
indices = np.argpartition(similarity, -5)[-5:]
#Input into the indices
results = df.iloc[indices]
results

,Manga ID,Japanese Title,Genres,Score
31,44489,宝石の国,"['Action', 'Fantasy', 'Seinen']",8.77
76,3649,Fate/Zero,"['Action', 'Fantasy', 'Supernatural']",8.61
348,8070,戦国妖狐,"['Action', 'Adventure', 'Demons', 'Drama', 'Sh...",8.22
375,77637,Helck,"['Action', 'Fantasy']",8.20
0,2,ベルセルク,"['Action', 'Adventure', 'Demons', 'Drama', 'Fa...",9.33